[package]
name = "raytracing"
version = "0.1.0"
authors = ["Carl", "Sami", "Daniel"]
edition = "2018"

[dependencies]
nalgebra = "0.16.12"
image = "0.20.1"
libraytracing = { path = "libraytracing" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false
