[package]
name = "raytracing"
version = "0.1.0"
authors = ["Carl", "Sami", "Daniel"]
edition = "2018"

[dependencies]
nalgebra = "0.16.12"
wavefront_obj = { git = "https://gitlab.com/ognarb/wavefront_obj.git" } 
image = "0.20.1"
rayon = "1.0.3"
